aptus4nurses/aptus4nurses/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Enter the app name in following
    # syntax for this to work
    path('guideline/', include("guideline.urls"))
]

aptus4nurses/guideline/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr  5 16:29:43 2023

@author: anagoncalves
"""

from django.urls import path
from django.contrib import admin
#now import the views.py file into this code

app_name = 'main'
from . import views
urlpatterns=[
  #path('', views.login_view, name = 'login'),
  path('', views.index, name = 'index'),
  path('index/', views.index, name = 'index'),
  #path('register/', views.register_nurse, name='register_nurse'),
  path('index_patient/', views.index_patient, name = 'index_patient'),
  path('search_patient/', views.search_patient, name = 'search_patient'),
  path('patient/<int:pk>/', views.patient, name='patient'),
  
  
  path('patients/new/', views.new_patient, name='new_patient'),
  path('new_patient_success/', views.new_patient_success, name = 'new_patient_success'),
  
  path('symptom_rating/<int:step>', views.symptom_rating, name='symptom_rating'),
  path('symptom_rating_function/<int:step>/', views.symptom_rating_function, name='symptom_rating_function'),
  path( 'form2/', views.form2_view, name = 'form2_view'),
  #path('save_rating/', views.save_rating, name='save_rating'),
  path('save_rating_success/', views.save_rating_success, name='save_rating_success'),
  #path('choose_sorting/', views.choose_sorting, name = 'choose_sorting'),
  path('save_selected_treatments/', views.save_selected_treatments, name='save_selected_treatments'),
  path('save_commentaries/', views.save_commentaries, name='save_commentaries'),
  path('save_final_occurrence/', views.save_final_occurrence, name='save_final_occurrence'),
  #path('provide-feedback/', views.provide_feedback, name='provide_feedback'),
  path('feedback/<int:occurrence_id>/', views.feedback_page, name ='feedback_page'),
  path('feedback_rating_function/<int:step>', views.feedback_rating_function, name ='feedback_rating_function'),
  
  path('treatment_suitability/', views.treatment_suitability, name = 'treatment_suitability'),

  #path('preview_rating/', views.preview_rating, name='preview_rating'),
  path('error/', views.error, name='error'),
  
  #path('edit_rating/', views.edit_rating, name='edit_rating'),
  path('edit_rating/<str:symptom_id>/', views.edit_rating, name='edit_rating'),
  
  path('occurrences/', views.patient_history, name='patient_history'),
  #path('recomendation/', views.recomendation, name='recomendation'),
  
  
  path('sys_guide/', views.sys_guide, name = 'sys_guide'),
  path('admin/', admin.site.urls)
]

aptus4nurses/guideline/models.py
# import the model


#De acordo com as seguintes perguntas selecione a opção que melhor se adequa ao paciente.from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

from django.db import models
import openpyxl


#create a new instacy

    

class Patient(models.Model):
    patientID = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    age = models.CharField(max_length=3)
    birthday = models.DateField()
    contact = models.CharField(max_length=20)

    # Read diagnosis options from Excel file
    diagnosis_options = []
    wb = openpyxl.load_workbook('CID-O.xlsx')
    sheet = wb.active
    
   
    for cell in sheet['A']:
        diagnosis_options.append((cell.value, cell.value))

    diagnosis = models.CharField(max_length=200, choices=diagnosis_options)

    def __str__(self):
        return self.patientID
    
class Symptom(models.Model):
    symptomID = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.symptomID
    
class Treatment(models.Model):
    category = models.CharField(max_length=40)
    name = models.CharField(max_length=40)
    symptoms = models.ManyToManyField(Symptom)
    
    def __str__(self):
        return self.name



class Suitability(models.Model):
    RATING_CHOICES = (
        ("Discordo completamente", "Discordo completamente"),
        ("Discordo", "Discordo"),
        ("Neutro", "Neutro"),
        ("Concordo", "Concordo"),
        ("Concordo completamente", "Concordo completamente"),
    )

    #suitability_id = models.AutoField(primary_key=True)  # This will add an auto-incrementing id field

    
    rating_1 = models.CharField(max_length=50, choices=RATING_CHOICES, default="Neutral")
    rating_2 = models.CharField(max_length=50, choices=RATING_CHOICES, default="Neutral")
    rating_3 = models.CharField(max_length=50, choices=RATING_CHOICES, default="Neutral")
    rating_4 = models.CharField(max_length=50, choices=RATING_CHOICES, default="Neutral")
    
   
    
class Occurrence(models.Model):
    occurrenceID = models.AutoField(primary_key=True)
    date_time = models.DateTimeField()
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    choosenTreatments = models.ManyToManyField(Treatment, blank=True)
    suitability = models.ForeignKey(Suitability, on_delete=models.CASCADE, null=True, blank=True)
    comments = models.TextField()
    
    # Add any other fields related to the occurrence
    
    def __str__(self):
        return f"{self.occurrenceID}"
    
class MSAS(models.Model):
    occurrence = models.ForeignKey(Occurrence, on_delete=models.CASCADE)
    symptom = models.ForeignKey(Symptom, on_delete=models.CASCADE)
    validation = models.BooleanField(default=False)
    frequency = models.IntegerField(default=0)
    severity = models.IntegerField(default=0)
    discomfort = models.IntegerField(default=0)   

    
class Feedback(models.Model):
    feedbackID = models.AutoField(primary_key=True)
    occurrence = models.ForeignKey(Occurrence, on_delete=models.CASCADE)
    symptom = models.ForeignKey(Symptom, on_delete=models.CASCADE)
    validation = models.BooleanField(default=False)
    frequency = models.IntegerField()
    severity = models.IntegerField()
    discomfort = models.IntegerField()
    #nurse = models.ForeignKey(Nurse, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return f"{self.feedbackID}"
    

aptus4nurses/guideline/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from datetime import datetime


from django.http import HttpResponse
from .models import Patient, Symptom, MSAS, Occurrence, Treatment, Feedback, Suitability
from .forms import PatientForm, ValidationForm, MSASForm, RemainingFieldsForm, SuitabilityForm

#from .forms import PatientSearchForm
# Create your views here.


def index(request):
    return render(request, 'aptus4nurses/index.html') 

def index_patient(request):
    """View of the page to search patients"""
    patients = Patient.objects.all()
    patients_count = Patient.objects.count()
    context = {
        'patients_count': patients_count,
        'patients': patients}
    return render(request, 'aptus4nurses/search_patient.html', context)

def patient(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    html = render_to_string('aptus4nurses/patient.html', {'patient': patient})
    return HttpResponse(html)

def sys_guide(request):
    selected_symptoms = Symptom.objects.all()
    treatments = Treatment.objects.all()
    
    # Getting the common treatments for all symptoms
    common_treatments = get_common_treatments(selected_symptoms)
    
    treatment_data = [(item[0].name, item[1], item[2]) for item in common_treatments]
    
    str_selected_symptoms = [symptom.name for symptom in selected_symptoms]
    #request.session['common_treatments'] = treatment_data
    
    #request.session['common_treatments'] = json.dumps(common_treatments)
    request.session['selected_symptoms'] = str_selected_symptoms
    
    #separar as tabelas por tipo de tratamento
    inter_farma = []
    inter_comple = []
    inter_psico = []
    inter_fisi = []
    sup_nutri = []
    
    for item in common_treatments:
        treat = item[0]
        if treat.category == 'Intervenções farmacológica':
            inter_farma.append(item)
            
        elif treat.category == 'Estratégias Complementares':
            inter_comple.append(item)
            
        elif treat.category == 'Intervençõees psicológicas':
            inter_psico.append(item)
            
        elif treat.category == 'Intervenções físicas':
            inter_fisi.append(item)
            
        else: #suplementos nutricioanis
            sup_nutri.append(item)
        
    table_farma = generate_table(treatments, selected_symptoms, inter_farma)
    table_comple = generate_table(treatments, selected_symptoms, inter_comple)
    table_psico = generate_table(treatments, selected_symptoms, inter_psico)
    table_fisi = generate_table(treatments, selected_symptoms, inter_fisi)

    table_nutri = generate_table(treatments, selected_symptoms, sup_nutri)
   
    n_symptoms = len(selected_symptoms)
    symptom_range = range(n_symptoms)

    context = {
        'common_treatments': common_treatments,
        'symptoms': selected_symptoms,
        'treatments': treatments,
        'table_farma': table_farma,
        'table_comple': table_comple,
        'table_psico': table_psico,
        'table_fisi': table_fisi,
        'table_nutri': table_nutri,
        'n_symptoms': symptom_range  
    }

    return render(request, 'aptus4nurses/sys_guide.html', context)


def search_patient(request):
    patient_id = request.GET.get('patient_id')
    
    if patient_id:
        try:
            patient = Patient.objects.get(id=patient_id)
            # Store patientID in the session
            request.session['patient_id'] = patient.patientID
            html = render_to_string('aptus4nurses/patient.html', {'patient': patient})
            return HttpResponse(html)
        except Patient.DoesNotExist:
            # Handle the case when the selected patient is not found
            # Return an appropriate message or redirect to an error page
            pass

    # Handle the case when no patient is selected or an error occurs
    patients = Patient.objects.all()
    return render(request, 'aptus4nurses/choose_patient.html', {'patients': patients})

def new_patient(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('new_patient_success')
        else:
            # Print form validation errors for debugging purposes
            print(form.errors)
    else:
        form = PatientForm()

    return render(request, 'aptus4nurses/new_patient.html', {'form': form})

def new_patient_success(request):
    return render(request, 'aptus4nurses/new_patient_success.html')

def symptom_rating(request, step=0):
    current_datetime = datetime.now()
    patient_id = request.session.get('patient_id')
    patient_ = Patient.objects.get(patientID=patient_id)
    
    occurrence = Occurrence.objects.create(date_time=current_datetime, patient = patient_)

    request.session['occurrence_id'] = occurrence.occurrenceID
    
    request.session['feedback_validation'] = False
    request.session['edit_validation'] = False

    return redirect('symptom_rating_function', step=0)

msas_instance_list = []

def validation_view(request):
    if request.method == 'POST':
        form = ValidationForm(request.POST)
        if form.is_valid():
            request.session['validation_data'] = form.cleaned_data
            return redirect('remaining_fields')
    else:
        form = ValidationForm()
    
    return render(request, 'validation_form.html', {'form': form})

def symptom_rating_function(request, step=0):
    symptoms = Symptom.objects.all().order_by('symptomID')
    num_symptoms = symptoms.count()

    occurrence_id = request.session.get('occurrence_id')
    occurrence = Occurrence.objects.get(occurrenceID=occurrence_id)

    str_symptom = str(symptoms[step])
    symptom_name = symptoms[step].name
    
    patient_name = occurrence.patient.name

    if request.method == 'POST':
        form = ValidationForm(request.POST)
        if form.is_valid():
            validation_data = form.cleaned_data
            
            if (validation_data['validation'] == 'True'): #tem de dar rating nos sintomas
                request.session['step'] = step
                request.session['str_ symptom'] = symptoms[step].name
                request.session['occurrence_id'] = occurrence.occurrenceID
                
                return redirect('form2_view')
                
            msas_instance = form.save(commit=False)
            msas_instance.symptom = symptoms[step]
            msas_instance.occurrence = occurrence

            next_step = step + 1
            if next_step < num_symptoms:
                msas_instance_list.append(msas_instance)
                return redirect('symptom_rating_function', step=next_step)
            else:
                msas_instance_list.append(msas_instance)
                context = {
                    'msas_instance_list': msas_instance_list,
                    'confirm_save': True,
                    'patient_name': patient_name
                    }
                return render(request, 'aptus4nurses/preview_rating.html', context)
                #return redirect('preview_rating', msas_instance_list)  # Redirect to the preview page

        else:
            print(form.errors)
    else:
        initial_data = {'symptom': symptoms[int(step)]} if int(step) < num_symptoms else {}
        form = ValidationForm(initial=initial_data)

    context = {
        'form': form,
        'step': int(step),
        'num_symptoms': num_symptoms,
        'symptom_name': symptom_name,
        'symptom': str_symptom,
        'next_step': step + 1,  # Pass the next step value to the template
        'patient_name': patient_name,
        'form_name': 'ValidationForm'
    }

    return render(request, 'aptus4nurses/symptom_rating.html', context)

def form2_view(request):
    step = request.session.get('step')
    
    str_symptom = request.session.get('str_ symptom')
    symptom = Symptom.objects.get(name=str_symptom)
    
    occurrenceID = request.session.get('occurrence_id')
    occurrence = Occurrence.objects.get(occurrenceID = occurrenceID)
    
    patient_name = occurrence.patient.name
    
    symptoms = Symptom.objects.all()
    num_symptoms = symptoms.count()
    
    if request.method == 'POST':
        form = RemainingFieldsForm(request.POST)
        if form.is_valid():
            msas_instance = form.save(commit=False)
            msas_instance.validation = True
            msas_instance.symptom = symptom
            msas_instance.occurrence = occurrence
            
            next_step = step + 1
            if request.session.get('feedback_validation'):
                num_symptoms = request.session.get('num_symptoms_feedback')
                
            if request.session.get('edit_validation'):
                # Create an instance of the MSAS model without saving it to the database yet

                symptom_id = request.session.get('symptom_id')
                msas_instance_list.insert(int(symptom_id)-1, msas_instance)

                context = {
                    'form': form,
                    'num_symptoms': num_symptoms,
                    # 'symptom': str_symptom,
                    'msas_instance_list': msas_instance_list,
                    'confirm_save': True,  # Add a flag to indicate confirmation step
                    'patient_name': patient_name
                }
                return render(request, 'aptus4nurses/preview_rating.html', context)
                
                
            if next_step < num_symptoms:
                msas_instance_list.append(msas_instance)
                if request.session.get('feedback_validation'):
                    return redirect('feedback_rating_function', step=next_step)
                else:
                    return redirect('symptom_rating_function', step=next_step)
            else:
                msas_instance_list.append(msas_instance)

aptus4nurses/guideline/templates/aptus4nurses/choose_patient.html
<!-- search_patient.html-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Patients</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://www.w3schools.com/lib/w3.js"></script>
    <style>
        body {
            background-color: #F6F6F2;
        }
        .w3-bar {
            background-color: #388087;
        }
        .w3-bar-item {
            color: white;
        }
        .page {
            padding-left: 270px;
            padding-top: 200px;
            color: #388087
            
        }
        .searchbox {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 30vh; 
            width: 100%;
        }
        .search {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 200px;
            width: 800px;
            background-color: #E2E2E2;
            color: black;
            border: 1px solid black;
            border-radius: 15px;
            margin: 0 auto;
        }
        .new_pati {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }
        
        .new_pati a.button {
            display: inline-block;
            padding: 8px 16px;
            background-color: #6FB3B8;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }
        p {
            width: 50%;
            background-color: #E2E2E2;
            padding: 5px;
            box-sizing: border-box;
            border: 1px solid black;
            text-align: left;
            margin: 0;
        }
        /* Add separation between patients */
        .patient-box {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #FFFFFF;
            border: 1px solid #CCCCCC;
            border-radius: 5px;
        }
        
    </style>
</head>
<body>

<!-- Start Content -->

<!-- Navigation (Stays on Top) -->
<div id= "navigation" class="w3-top w3-bar w3-left" >
    <a href="{% url 'index' %}" class="w3-bar-item w3-button"> Home</a>
    <a href="{% url 'index_patient' %}" class="w3-bar-item w3-button">Página Pacientes</a>
    <a href="{% url 'sys_guide' %}" class="w3-bar-item w3-button">Guideline para gestão de sintomas</a>
</div>

<!-- About -->
<div id="page" class="w3-container w3-padding-32 page" style="margin-top: 50px;">
    <h1 class="w3-left" style="font-size: 35px;">Página Pacientes</h1>
</div>
  
<!-- Search -->
<div id="results">
    {% if patients %}
        <ul>
            {% for patient in patients %}
              <li>
                <div class="patient-box" style="color: black;">
                    <p><strong>Nome Completo:</strong> {{ patient.name}}</p>
                    <p><strong>Número de Utente:</strong> {{ patient.patientID}}</p>
                </div>
              </li>
            {% endfor %}
          </ul>
    {% else %}
        <p>No patients found.</p>
    {% endif %}
</div>

<div class="new_pati">
    <a href="{%url 'new_patient' %}" class="button">Criar novo paciente</a>
</div>

<!-- End Content -->
</body>
</html>

aptus4nurses/guideline/templates/aptus4nurses/error.html
<!-- save_rating_success.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
</body>
</html>

aptus4nurses/guideline/templates/aptus4nurses/feedback_page.html
<!-- patient_history.html-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Aptus4nurses Patients</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://www.w3schools.com/lib/w3.js"></script>
    <style>
        body {
            background-color: #F6F6F2;
        }
        .w3-bar {
            background-color: #388087;
        }
        .w3-bar-item {
            color: white;
        }
        .page {
            padding-left: 50px;
            padding-top: 200px;
            color: #388087
        }
        .searchbox {
            padding-left: 50px;
            color: #388087
        }
        .search{
            justify-content: left;
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 200px;
            width: 400px;
            background-color: #E2E2E2;
            color: black;
            border: 1px solid black;
            border-radius: 15px;
            margin: 60px;
        }
        p {
            width: 50%;
            background-color: #E2E2E2;
            padding: 5px;
            box-sizing: border-box;
            border: 1px solid black;
            text-align: left;
            margin: 0;
        }
        .button {
           text-align: center;
           display: flex;
           flex-wrap: wrap;
           justify-content: center;
           align-items: center;
           height: 80px;
           width: 120px;
           background-color: #6FB3B8;
           color: black;
           border: none;
           border-radius: 15px;
           margin: 60px;
       }
        
    </style>
</head>
<body>

<!-- Start Content -->

<!-- Navigation (Stays on Top) -->
<div id= "navigation" class="w3-top w3-bar w3-left" >
    <a href="{% url 'index' %}" class="w3-bar-item w3-button"> Home</a>
    <a href="{% url 'index_patient' %}" class="w3-bar-item w3-button">Página Pacientes</a>
    <a href="{% url 'sys_guide' %}" class="w3-bar-item w3-button">Guideline para gestão de sintomas</a>
</div>

<!-- About -->
<div id="page" class="w3-container w3-padding-32 page" style="margin-top: 50px;">
    <h1 class="w3-left" style="font-size: x-large;">Feedback page {{occurrence_id}}</h1>
</div>


<!-- Go back button -->
<button class="button" onclick="goBack()">Go Back</button>

<script>
  function goBack() {
    window.history.back();
  }
</script>
  
<!-- Go back button -->
<div class="container">
	<a href="{% url 'index_patient' %}" class="button">Voltar página de pacientes</a>
</div>

<!-- End Content -->
</body>
</html>

aptus4nurses/guideline/templates/aptus4nurses/suitability.html
<!-- suitability.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WikiCare Patients</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://www.w3schools.com/lib/w3.js"></script>
    <style>
        body {
            background-color: #F6F6F2;
        }
        .w3-bar {
            background-color: #388087;
        }
        .w3-bar-item {
            color: white;
        }
        .page {
            padding-left: 270px;
            padding-top: 200px;
            padding-bottom: 10px; /* Adjust the bottom padding as needed */
            margin-bottom: -100px; /* Adjust the negative margin as needed */
            color: #388087;
        }
        .searchbox {
            padding-left: 50px;
            color: #388087;
        }
        .search {
            justify-content: left;
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 200px;
            width: 400px;
            background-color: #E2E2E2;
            color: black;
            border: 1px solid black;
            border-radius: 15px;
            margin: 60px;
        }
        p {
            width: 75%;
            padding: 5px;
            box-sizing: border-box;
            text-align: left;
            margin: 0;
        }
        .button {
            text-align: center;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
            height: 80px;
            width: 120px;
            background-color: #6FB3B8;
            color: white;
            border: none;
            border-radius: 15px;
            margin: 60px;
        }
        .success-message {
            float: right;
            width: 400px;
            padding: 20px;
            background-color: #E2E2E2;
            border: 1px solid black;
            border-radius: 15px;
            margin-top: 60px;
        }
        .black-text {
            color: black;
        }
        .radio-group {
            margin-top: 10px;
        }
    
        .radio-group label {
            margin-right: 15px; /* Adjust this value for the desired spacing */
        }
    </style>
</head>
<body>
<!-- Start Content -->
<!-- Navigation (Stays on Top) -->
<div id= "navigation" class="w3-top w3-bar w3-left" >
    <a href="{% url 'index' %}" class="w3-bar-item w3-button"> Home</a>
    <a href="{% url 'index_patient' %}" class="w3-bar-item w3-button">Página Pacientes</a>
    <a href="{% url 'sys_guide' %}" class="w3-bar-item w3-button">Guideline para gestão de sintomas</a>
</div>

<!-- About -->
<div id="page" class="w3-container w3-padding-32 page" style="margin-top: 40px;">
    <h1 class="w3-left" style="font-size: x-large;">Área Pessoal: <span class="black-text">{{patient.name}}</span></h1>
</div>

<div id="page" class="w3-container w3-padding-32 page" style="margin-top: 40px;">
    <h2 class="w3-left" style="font-size: x-large;"><span class="black-text">Avaliar adequabilidade da intervenção</span></h2>
    <br>
    <br>
    <br>
    <p class="black-text" >De forma a compreender melhor a perspetiva do paciente sobre a recomendação que lhe foi feita, peça ao paciente para avaliar as seguintes frases:</p>
</div>

<form method="POST" action="{% url 'treatment_suitability' %}" style="margin-left: 270px; margin-top: 100px">
    {% csrf_token %}

    <label for="id_rating_1">1 - As intervenções selecionadas parecem ser <strong>adequadas</strong>:</label>
    <div class="radio-group" style="margin-left: 50px">

        {% for choice in form.rating_1.field.choices %}
        <input type="radio" id="id_rating_1_{{ forloop.counter0 }}" name="{{ form.rating_1.name }}" value="{{ choice.0 }}" {% if choice.0 == form.rating_1.value %}checked{% endif %}>
        <label for="id_rating_1_{{ forloop.counter0 }}">{{ choice.1 }}</label>
        {% endfor %}
    </div>
    <br>
    <br>
    <label for="id_rating_2">2 - As intervenções selecionadas parecem ser <strong>apropriadas</strong>:</label>
    <div class="radio-group" style="margin-left: 50px">
        {% for choice in form.rating_2.field.choices %}
        <input type="radio" id="id_rating_2_{{ forloop.counter0 }}" name="{{ form.rating_2.name }}" value="{{ choice.0 }}" {% if choice.0 == form.rating_2.value %}checked{% endif %}>
        <label for="id_rating_2_{{ forloop.counter0 }}">{{ choice.1 }}</label>
        {% endfor %}
    </div>
    <br>
    <br>
    <label for="id_rating_3">3 - As intervenções selecionadas parecem ser <strong>aplicáveis</strong>:</label>
    <div class="radio-group" style="margin-left: 50px">
        {% for choice in form.rating_3.field.choices %}
        <input type="radio" id="id_rating_3_{{ forloop.counter0 }}" name="{{ form.rating_3.name }}" value="{{ choice.0 }}" {% if choice.0 == form.rating_3.value %}checked{% endif %}>
        <label for="id_rating_3_{{ forloop.counter0 }}">{{ choice.1 }}</label>
        {% endfor %}
    </div>
    <br>
    <br>
    <label for="id_rating_4">4 - As intervenções selecionadas parecem ser <strong>uma boa opção</strong>:</label>
    <div class="radio-group" style="margin-left: 50px">
        {% for choice in form.rating_4.field.choices %}
        <input type="radio" id="id_rating_4_{{ forloop.counter0 }}" name="{{ form.rating_4.name }}" value="{{ choice.0 }}" {% if choice.0 == form.rating_4.value %}checked{% endif %}>
        <label for="id_rating_4_{{ forloop.counter0 }}">{{ choice.1 }}</label>
        {% endfor %}
    </div>
    <br>
    <input type="submit" class="button rounded-square" style="width: 200px; margin-left: 560px; margin-top: 10px" value="Guardar avaliação">
</form>

<!-- End Content -->
</body>
</html>